name: Generate STL files
run-name: Generate STL files
on: [push, pull_request]
jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Install openscad
        uses: awalsh128/cache-apt-pkgs-action@latest # Cached install of openscad
        with:
          packages: openscad

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Install openscad
      #  run: sudo apt-get install openscad
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run python script
        run: python ${{ github.workspace }}/make.py
