name: Generate STL files
run-name: Generate STL files
on: [push, pull_request]
jobs:
  generation:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Install Qt # openscad requires qt?
        uses: jurplel/install-qt-action@v4

      - name: Install openscad
        uses: awalsh128/cache-apt-pkgs-action@latest # Cached install of openscad
        with:
          packages: openscad

      - name: Set up python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run python script
        run: python ${{ github.workspace }}/make.py
