# Almost the same as generate-files.yml but also releases files
name: Release
run-name: Release
on:
  push:
    branches: 
      - main
jobs:
  generation:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - name: Install openscad
        run: sudo snap install openscad-nightly

      - name: Set up python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run python script
        run: |
          python ${{ github.workspace }}/make.py --openscad_path="openscad-nightly"

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

      - name: Zip files
        run: | 
          for b in build/*
          do
            zip -r "$(basename '$b').zip" $b
          done
          
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
            files: "*.zip"
            fail_on_unmatched_files: true
            name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
            tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
            token: ${{secrets.GITHUB_TOKEN}}
            generate_release_notes: true
            
